# This is a basic workflow to help you get started with Actions

name: SharedCall

on:
  workflow_call:
    inputs:
      ModuleName:
        required: true
        type: string
      GitBranch:
        required: true
        type: string
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  Dev-Deployment:
    runs-on: ubuntu-latest
    environment: Dev
    needs: build
    steps:
      - name: Run a one-line script
        run: |
          echo  Dev-Deployment
          echo ${{github.event.input.ModuleName}}
          echo ${{github.event.input.GitBranch}}
          env
 
          
  prod-Deployment:
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    steps:
      - name: Run a one-line script
        run: |
          echo  prod-Deploymen
          echo ${{github.event.input.ModuleName}}
          echo ${{github.event.input.GitBranch}}
 
