# This is a basic workflow to help you get started with Actions

name: SharedCall

on:
  workflow_call:
    inputs:
      ModuleName:
        required: true
        type: string
      GitBranch:
        required: true
        type: string
      ProdRelease:
        required: true
        type: boolean
env:
  one: 1
  two: kknd
  three: "ddd"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - id: PopulateValue
        run: |
          echo Add other actions to build,
          a="sss"
          echo "three='new'" >> $GITHUB_ENV 
          echo "four=$a" >> $GITHUB_ENV 
          echo "::set-output name=test1::hello" 
          env
    outputs:
      four : ${{ steps.PopulateValue.outputs.test1 }}
        
          
  Dev-Deployment:
    runs-on: ubuntu-latest
    environment: Dev
    needs: build
    steps:
      - name: Run a one-line script
        run: |
          echo  Dev-Deployment
          echo "${{github.event.inputs.ModuleName}}"
          echo "${{github.event.inputs.GitBranch}}"
          echo "four ${{ needs.build.outputs.test1 }}"
 
          env
 
          
  prod-Deployment:
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    if: ${{github.event.inputs.ProdRelease == 'true' }}
    steps:
      - name: Run a one-line script
        run: |
          echo  prod-Deploymen
          echo "${{github.event.inputs.ModuleName}}"
          echo "${{github.event.inputs.GitBranch}}"
          env
 
