# This is a basic workflow to help you get started with Actions

name: CallerA

# Controls when the workflow will run
on:
 workflow_dispatch:
   inputs:
     ModuleName: 
      type: choice
      required: true
      description: 'Module Name'
      options:
        - aa
        - bb
     GitBranch:
       type: string
       description: 'Git Branch'
       required: true
 
          
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  jobSel:
   runs-on: ubuntu-latest
   steps:
    - name: checkout Branch
      uses: actions/checkout@v2.4.2
      with:
       ref:  ${{github.event.inputs.GitBranch}}
    - name: setup input
      shell: bash
      run: |
       echo "ModuleName=${{ModuleName}}" >> $GITHUB_ENV
       echo "GitBranch=${{GitBranch}}" >> $GITHUB_ENV
       echo "${{GitBranch}}"
       echo  "${{ModuleName}"
       echo "no quotation"
       echo ${{GitBranch}}
       echo ${{ModuleName}}
    - name: list env
      shell: bash
      run: |
       env
 
       
  
  
  callSharedJob:
     needs: jobSel
     uses: yemail/githubWorkflowTest/.github/workflows/SharedTestDeploy.yml@main
     with:
       ModuleName: "${{github.event.inputs.ModuleName}}"
       GitBranch : "${{github.event.inputs.GitBranch}}"

 
