# This is a basic workflow to help you get started with Actions

name: CallerA

# Controls when the workflow will run
on:
 workflow_dispatch:
   inputs:
     ModuleName: 
      type: choice
      required: true
      description: 'Module Name'
      options:
        - aa
        - bb
     GitBranch:
       type: string
       description: 'Git Branch'
       required: true
       
     ProdRelease:
       required: true
       type: boolean       

          
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  jobSel:
   runs-on: ubuntu-latest
   steps:
    - name: checkout Branch
      uses: actions/checkout@v3
      with:
       ref:  ${{github.event.inputs.GitBranch}}

    - name: list env
      shell: bash
      run: |
       env
 
       
  
  
  callSharedJob:
     needs: jobSel
     uses: yemail/githubWorkflowTest/.github/workflows/SharedTestDeploy.yml@main
     with:
       ModuleName: "${{github.event.inputs.ModuleName}}"
       GitBranch : "${{github.event.inputs.GitBranch}}"
       ProdRelease :  ${{  github.event.inputs.ProdRelease == 'true' }}
       TestA: aaaabbbbc

 
