# This is a basic workflow to help you get started with Actions

name: CallerA

# Controls when the workflow will run
on:
 workflow_dispatch:
   inputs:
     ModuleName:
       type: choice
       required: true
       options:
         - aa
         - bb
     GitBranch:
       type: string
       required: true
 
          
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  jobSel:
   runs-on: ubuntu-latest
   steps:
    - name: checkout Branch
      uses: actions/checkout@v2.4.2
      with:
       ref:  ${{github.event.input.GitBranch}}
  
  callSharedJob:
     needs: jobSel
     uses: yemail/githubWorkflowTest/.github/workflows/SharedTestDeploy.yml@main
     with:
       ModuleName: "${{github.event.input.ModuleName}}"
       GitBranch : "${{github.event.input.GitBranch}}"

 
